name: Run Python Tests
on:
  push:
    branches:
      - master
      - tests
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - name: Install Python 3
        run: |
          sudo apt-get install python3
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install mido pytest
      - name: Run tests with pytest
        run: |
          cd ..
          echo "uffa"
          ls -l .
          echo "boring"
          ls -l ..
          pytest 
