name: Run Python Tests
on:
  push:
    branches:
      - master
      - tests
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/[email protected]
      - name: Install Python 3
        uses: actions/[email protected]
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mido
      - name: Run tests with pytest
        run: pytest 
