name: Run Python Tests
on:
  push:
    branches:
      - master
      - tests
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python 3
        run: |
          apt-get install python -y
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mido
      - name: Run tests with pytest
        run: pytest 
